namespace MusicApp.Data.Entities;

// It represents the schema of the 'Songs' table and nothing else.
[Table("Songs")]
public class SongEntity
{
    /// <summary>Primary key. Generated by the database using NEWSEQUENTIALID().</summary>
    [Key]
    public Guid Id { get; set; }

    /// <summary>Song title. Required, max 200 characters.</summary>
    [Required]
    [MaxLength(200)]
    public required string Title { get; set; }

    /// <summary>Artist name. Required, max 100 characters.</summary>
    [Required]
    [MaxLength(100)]
    public required string Artist { get; set; }

    /// <summary>Album name. Optional, max 100 characters.</summary>
    [MaxLength(100)]
    public string? AlbumName { get; set; }

    /// <summary>Duration of the track.</summary>
    public TimeSpan Duration { get; set; }

    /// <summary>Original release date of the song.</summary>
    public DateTime ReleasedDate { get; set; }

    // [Audit Fields]: Internal metadata — not exposed in SongResponse DTOs.
    /// <summary>UTC timestamp of when the record was created.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Identity of the user who uploaded the song.</summary>
    public string? CreatedBy { get; set; }
}
